### PR TITLE
Upgrade Travis to new container based infrastructure

### PR DESCRIPTION
**Pull request by danielcompton**
Builds are faster on container infrastructure.

### CODE REVIEW

**Comment by danielcompton** [comment]
Any interest in this PR? I can close it otherwise.

**Comment by danielcompton** [comment]
Is this useful? Otherwise I can close it.

**Comment by danielcompton** [comment]
Travis says that this repository isn't an active repo any more: https://travis-ci.org/weavejester/ragtime. Would you be able to re-enable it for CI checks?

**Comment by weavejester** [comment]
Sure. Re-enabled. I'm not sure why it was deactivated.

**Pull request closed without merging**
