### PR TITLE
Sort JDBC migrations by ':id'

### PR DESCRIPTION
**Pull request by xsc**
See #111.

### CODE REVIEW

**Comment by weavejester** [comment]
Can you change "See #111." to "Fixes #111."?

**Comment by xsc** [comment]
Done in de01146.

**Comment by danielcompton** [comment]
Would it be good to add some tests for this behaviour too, as it's a little bit subtle?

**Comment by weavejester** [comment]
Tests would be good :+1:

**Comment by xsc** [comment]
Sorry for the latency. Tests are adjusted now, failing on master:

```
lein test :only ragtime.jdbc-test/test-load-resources

FAIL in (test-load-resources) (jdbc_test.clj:72)
expected: (= ["001-test" "002-bar" "003-test" "004-test" "005-test" "006-test"] (p/applied-migration-ids db))
  actual: (not (= ["001-test" "002-bar" "003-test" "004-test" "005-test" "006-test"] ("001-test" "002-bar" "006-test" "003-test" "004-test" "005-test")))

lein test :only ragtime.jdbc-test/test-load-directory

FAIL in (test-load-directory) (jdbc_test.clj:59)
expected: (= ["001-test" "002-bar" "003-test" "004-test" "005-test" "006-test"] (p/applied-migration-ids db))
  actual: (not (= ["001-test" "002-bar" "003-test" "004-test" "005-test" "006-test"] ("001-test" "002-bar" "006-test" "003-test" "004-test" "005-test")))

Ran 7 tests containing 17 assertions.
2 failures, 0 errors.
Tests failed.
```

**Comment by weavejester** [comment]
Thanks! Can you squash your commits? Then I'll merge.

**Pull request merged**
