### PR TITLE
Fix condition check comparing migrations to discards

### LINKED ISSUE #109: Calling ragtime.repl/rollback with a non-existant migration has different effects, depending on the current database state
Hi there,

I'm seeing the following different effects when calling `ragtime.repl/rollback` with a non-existant migration, which from my basic analysis seems to depend on the current database state of migrations, and/or whether there are existing migrations available to apply.

I just wanted to check my understanding:
1. When calling with database state at 001-first-migration, if 002-second-migration is available via `ragtime.jdbc/load-resources`, a call to `ragtime.repl/rollback` with migration `non-existant-id` results in `Exception Could not find migration 'non-existant-id' in database  ragtime.core/rollback-to (core.clj:66)` (to me, this exception makes sense.)
2. When calling with database state at 002-second-migration, with no more migrations available via `ragtime.jdbc/load-resources`, a call to `ragtime.repl/rollback` with migration `non-existant-id` results in a rollback of all migrations, and the function returns `nil`. (this I do not understand.)

Should I expect these different effects in the case of a non-existant migration?

I'm using version 0.6.1.

Thanks :)

### PR DESCRIPTION
**Pull request by welovelain**
Fixes #109 .

### CODE REVIEW

**Comment by weavejester** [comment]
Thanks! Is it possible for you to add a test as well?

**Comment by welovelain** [comment]
Added test and squashed commits, is it okay?

**Comment by weavejester** [comment]
Yes, almost perfect, except that your indentation on line 99 is one space instead of two, I believe.

**Comment by welovelain** [comment]
Oops, fixed indentation

**Comment by welovelain** [comment]
ehm... bump?

**Comment by weavejester** [comment]
Sorry, this slipped from my inbox.

**Comment by weavejester** [comment]
Released as 0.6.4

**Pull request merged**
