### PR TITLE
Handle CLJ migrations (fixes #125)

### LINKED ISSUE #125: CLJ migrations
Handle migrations as an CLJ files.

### PR DESCRIPTION
**Pull request by mariusz-jachimowicz-83**
Handle CLJ migrations (fixes #125)

### CODE REVIEW

**Comment by weavejester** [comment]
I'd prefer this functionality be a third-party library to begin with, especially since your implementation isn't specific to JDBC.

**Comment by mariusz-jachimowicz-83** [comment]
Ok. I will create it in my repo.

**Comment by weavejester** [comment]
> Any chance this be leveraged in Ragtime docs?

By "leveraged in the Ragtime docs" do you mean, "add a link to the ragtime-clj in the README"?

**Comment by sanel** [comment]
Yes :)

**Comment by weavejester** [comment]
I've added a link in the README to a "Third-party Libraries" wiki page that has a link to ragtime-clj.

**Pull request closed without merging**
